### ISSUE TITLE
which Db are used ? used or not ?

### ISSUE THREAD

**Issue by ranjit485** [thejunghare/offlineTimeTablesMSRTCBuses#1]

**Comment by ranjit485** [comment]
### sorry ! my  fault 
![Capture](https://github.com/thejunghare/offlineTimeTablesMSRTCBuses/assets/71892385/530a31c6-bb79-41be-b07b-4ba69a5161f0)

**Comment by thejunghare** [comment]
I am planning to use firebase and developing an api using golang
